version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "1339:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    restart: "on-failure"

  db:
    hostname: db
    image: postgres:13.0-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env

  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py create_users &&
                    python manage.py create-banners &&
                    python manage.py create-cinema-halls-session-movies &&
                    python manage.py create_pages &&
                    python manage.py collectstatic &&
                    gunicorn --bind 0.0.0.0:8000 kinocms.wsgi"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: "on-failure"
    image: kinocms-app

volumes:
  postgres_data:
  media_volume:
  static_volume:
