version: '3.9'

services:
  db:
    hostname: db
    image: postgres:13.0-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - .env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
