# Generated by Django 4.0.6 on 2022-07-17 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Назва кінотеатру')),
                ('description', models.TextField(verbose_name='Опис')),
                ('condition', models.TextField(verbose_name='Умови')),
                ('logo', models.ImageField(upload_to='cinema/cinema/logo/', verbose_name='Логотип')),
                ('banner_photo', models.ImageField(upload_to='cinema/cinema/banner_photo/', verbose_name='Фото верхнього баннера')),
            ],
            options={
                'verbose_name_plural': 'Кінотеатри',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=55)),
                ('keyword', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер зала')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('scheme', models.ImageField(upload_to='cinema/hall/scheme/', verbose_name='Схема зала')),
                ('banner_photo', models.ImageField(upload_to='cinema/hall/banner_photo/', verbose_name='Верхній баннер')),
                ('row_amount', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('seat_amount', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='Кінотеатр')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Галерея картинок')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='SEO блок')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Галерея картинок'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='SEO блок'),
        ),
    ]
