# Generated by Django 4.0.6 on 2022-07-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_cinema_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='SEO блок'),
        ),
    ]
