# Generated by Django 4.0.6 on 2022-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_seo_description_seo_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис залу'),
        ),
    ]
