# Generated by Django 4.0.6 on 2022-08-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_hall_cinema_id_alter_hall_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='Кінотеатр'),
        ),
    ]
