# Generated by Django 4.0.6 on 2022-08-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_hall_cinema_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo', verbose_name='SEO блок'),
        ),
    ]
