# Generated by Django 4.0.6 on 2022-08-19 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_hall_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
