# Generated by Django 3.2.12 on 2022-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_hall_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='condition_ru',
            field=models.TextField(null=True, verbose_name='Умови'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='condition_uk',
            field=models.TextField(null=True, verbose_name='Умови'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Назва кінотеатру'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=55, null=True, verbose_name='Назва кінотеатру'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Опис залу'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис залу'),
        ),
    ]
