# Generated by Django 3.2.12 on 2022-09-15 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_auto_20220915_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
