# Generated by Django 3.2.12 on 2022-09-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_hall_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Галерея картинок'),
        ),
    ]
