# Generated by Django 4.1 on 2022-08-31 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_gallery_alter_page_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
