# Generated by Django 4.1 on 2022-09-01 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
