# Generated by Django 4.1 on 2022-09-01 20:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_hall_created_at'),
        ('page', '0005_mainpage_status_alter_mainpage_phone_number_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='phone_number_first',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo'),
        ),
    ]
