# Generated by Django 4.1 on 2022-09-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_hall_created_at'),
        ('page', '0006_alter_mainpage_phone_number_first_alter_mainpage_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=55, verbose_name='Назва кінотеатру')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('coordinates', models.CharField(max_length=55, verbose_name='Координати')),
                ('logo', models.FileField(upload_to='contacts/')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
    ]
