# Generated by Django 4.1 on 2022-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='logo',
            field=models.ImageField(upload_to='contacts/'),
        ),
    ]
