# Generated by Django 4.1 on 2022-09-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_contacts_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='logo',
            field=models.ImageField(upload_to='contacts/', verbose_name='Лого'),
        ),
    ]
