# Generated by Django 4.1 on 2022-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_contacts_status_alter_contacts_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='seo',
        ),
    ]
