# Generated by Django 3.2.12 on 2022-09-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.CharField(max_length=200, verbose_name='Координати'),
        ),
    ]
