# Generated by Django 3.2.12 on 2022-09-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_contacts_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.CharField(max_length=500, verbose_name='Координати'),
        ),
    ]
