# Generated by Django 4.1 on 2022-09-02 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_hall_created_at'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seo'),
        ),
    ]
