# Generated by Django 3.2.12 on 2022-09-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220915_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('event', 'Event')], max_length=55, null=True),
        ),
    ]
