# Generated by Django 4.0.6 on 2022-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Назва фільма')),
                ('description', models.TextField(verbose_name='Опис')),
                ('main_photo', models.ImageField(upload_to='movie/', verbose_name='Головна картинка')),
                ('trailer_url', models.URLField(verbose_name='Посилання на трейлер')),
                ('type_2D', models.BooleanField(default=True)),
                ('type_3D', models.BooleanField(default=True)),
                ('type_IMAX', models.BooleanField(default=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.gallery', verbose_name='Галерея картинок')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
