# Generated by Django 4.1 on 2022-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220829_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.AddField(
            model_name='session',
            name='type_2D',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='type_3D',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='type_IMAX',
            field=models.BooleanField(default=False),
        ),
    ]
