# Generated by Django 3.2.12 on 2022-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_session_type_session_type_2d_session_type_3d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='type_2D',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type_3D',
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=10, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
