# Generated by Django 4.0.6 on 2022-07-17 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Імʼя')),
                ('surname', models.CharField(max_length=55, verbose_name='Прізвище')),
                ('alias', models.CharField(max_length=55, verbose_name='Псевдонім')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=55, verbose_name='Пароль')),
                ('card_number', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Номер карти')),
                ('language', models.CharField(choices=[('ukrainian', 'Українська'), ('russian', 'Російська')], max_length=55, verbose_name='Мова')),
                ('sex', models.IntegerField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], verbose_name='Стать')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('city', models.CharField(max_length=55, verbose_name='Місто')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Номер ряду')),
                ('seat_number', models.IntegerField(verbose_name='Номер місця')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.simpleuser')),
            ],
        ),
    ]
