# Generated by Django 4.0.6 on 2022-08-19 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_simpleuser_user_simpleuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='card_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Номер карти'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='city',
            field=models.CharField(default='Chernivtsi', max_length=55, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='language',
            field=models.CharField(choices=[('ukrainian', 'Українська'), ('russian', 'Російська')], default='ukrainian', max_length=55, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(default='Test', max_length=55, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=1509798561, max_digits=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Чоловік'), (2, 'Жінка')], default=1, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='surname',
            field=models.CharField(default='Test', max_length=55, verbose_name='Прізвище'),
        ),
    ]
