# Generated by Django 4.0.6 on 2022-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_simpleuser_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='card_number',
            field=models.IntegerField(default=4119499118528993, verbose_name='Номер карти'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=models.IntegerField(default=65458754, verbose_name='Телефон'),
        ),
    ]
