# Generated by Django 4.0.6 on 2022-08-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_simpleuser_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='alias',
            field=models.CharField(max_length=200, unique=True, verbose_name='Псевдонім'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='city',
            field=models.CharField(default='Chernivtsi', max_length=200, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(default='Test', max_length=200, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='surname',
            field=models.CharField(default='Test', max_length=200, verbose_name='Прізвище'),
        ),
    ]
