# Generated by Django 4.0.6 on 2022-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_simpleuser_alias_alter_simpleuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='password_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Підтвердження паролю'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='birthday',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер карти'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Чоловік'), (1, 'Жінка')], default=0, verbose_name='Стать'),
        ),
    ]
