# Generated by Django 4.0.6 on 2022-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_simpleuser_password_2_alter_simpleuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], default=0, max_length=55, verbose_name='Стать'),
        ),
    ]
