# Generated by Django 4.0.6 on 2022-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_simpleuser_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleuser',
            old_name='password_2',
            new_name='password2',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='sex',
            field=models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], default='male', max_length=55, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Прізвище'),
        ),
    ]
