# Generated by Django 4.0.6 on 2022-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_password_2_simpleuser_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='password2',
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Підтвердження паролю'),
        ),
    ]
