# Generated by Django 4.0.6 on 2022-08-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_simpleuser_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='password1',
        ),
    ]
