# Generated by Django 4.0.6 on 2022-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_simpleuser_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
