# Generated by Django 4.0.6 on 2022-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_simpleuser_password1_alter_simpleuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
