# Generated by Django 4.1 on 2022-08-31 13:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_simpleuser_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
