# Generated by Django 4.1 on 2022-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_simpleuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер карти'),
        ),
    ]
