# Generated by Django 4.0.6 on 2022-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='banner/background_banner/')),
                ('background', models.IntegerField(choices=[(1, 'Фото на фон'), (2, 'Просто фон')])),
            ],
        ),
        migrations.CreateModel(
            name='MainTopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turning_speed', models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')])),
                ('turned_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turning_speed', models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')])),
                ('turned_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBannerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='banner/news_banner/')),
                ('url', models.URLField()),
                ('news_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.newsbanner')),
            ],
        ),
        migrations.CreateModel(
            name='MainTopBannerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='banner/main_top_banner/')),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('main_top_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.maintopbanner')),
            ],
        ),
    ]
