# Generated by Django 4.0.6 on 2022-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='background',
            field=models.IntegerField(choices=[(1, 'Фото на фон'), (2, 'Просто фон')], default=1),
        ),
    ]
