# Generated by Django 3.2.12 on 2022-08-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_backgroundbanner_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintopbanner',
            name='turning_speed',
            field=models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5),
        ),
        migrations.AlterField(
            model_name='maintopbannerphoto',
            name='main_top_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.maintopbanner'),
        ),
        migrations.AlterField(
            model_name='maintopbannerphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/main_top_banner/'),
        ),
        migrations.AlterField(
            model_name='maintopbannerphoto',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintopbannerphoto',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsbannerphoto',
            name='news_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.newsbanner'),
        ),
        migrations.AlterField(
            model_name='newsbannerphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/news_banner/'),
        ),
        migrations.AlterField(
            model_name='newsbannerphoto',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
