# Generated by Django 3.2.12 on 2022-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20220827_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbanner',
            name='turning_speed',
            field=models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5),
        ),
    ]
